# Generated by Django 6.0.1 on 2026-01-26 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_faculty_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='is_locked',
            field=models.BooleanField(default=True, help_text='Prevent modifications to slot'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='slot_type',
            field=models.CharField(choices=[('MORNING', 'Morning Period'), ('AFTERNOON', 'Afternoon Period'), ('LUNCH', 'Lunch Break')], default='MORNING', max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('LAB', 'Lab'), ('ELECTIVE', 'Elective')], max_length=10),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(default=datetime.time(9, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(default=datetime.time(10, 0)),
            preserve_default=False,
        ),
    ]
